/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mmmi.mdsd.iot_dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IoTDSLRuntimeModule extends AbstractIoTDSLRuntimeModule {
}
