/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mmmi.mdsd.iot_dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IoTDSLStandaloneSetup extends IoTDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new IoTDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
